2021-07-23 09:24:08,949 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 09:24:08,950 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 09:24:10,564 - WARNING : aiohttp could not be imported. Async example will not work
Traceback (most recent call last):
  File "C:\Users\ethan\Documents\simExcel\examples\asyncfunc.py", line 24, in <module>
    import aiohttp
  File "build/x64/py38/res/release/pyxll.py", line 8206, in __import_hook
ModuleNotFoundError: No module named 'aiohttp'
2021-07-23 09:24:18,104 - INFO : This product is licensed to 
2021-07-23 09:24:18,104 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 09:24:29,291 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-23 09:24:52,713 - ERROR : Exception in Tkinter callback
2021-07-23 09:24:52,732 - ERROR : Traceback (most recent call last):
2021-07-23 09:24:52,733 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 09:24:52,733 - ERROR :     return self.func(*args)
2021-07-23 09:24:52,733 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 84, in on_button1
2021-07-23 09:24:52,733 - ERROR :     self.button1.config(relief=tk.SUNKEN)
2021-07-23 09:24:52,733 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1637, in configure
2021-07-23 09:24:52,733 - ERROR :     return self._configure('configure', cnf, kw)
2021-07-23 09:24:52,733 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1627, in _configure
2021-07-23 09:24:52,733 - ERROR :     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2021-07-23 09:24:52,733 - ERROR : _tkinter.TclError: invalid command name ".!toplevel2.!distributiondata.!button"
2021-07-23 09:25:00,656 - INFO : callbacks.on_close: PyXLL is closing
2021-07-23 09:27:44,437 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 09:27:44,438 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 09:27:44,497 - WARNING : aiohttp could not be imported. Async example will not work
Traceback (most recent call last):
  File "C:\Users\ethan\Documents\simExcel\examples\asyncfunc.py", line 24, in <module>
    import aiohttp
  File "build/x64/py38/res/release/pyxll.py", line 8206, in __import_hook
ModuleNotFoundError: No module named 'aiohttp'
2021-07-23 09:27:44,551 - INFO : This product is licensed to 
2021-07-23 09:27:44,551 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 09:27:51,523 - ERROR : Exception in Tkinter callback
2021-07-23 09:27:51,523 - ERROR : Traceback (most recent call last):
2021-07-23 09:27:51,523 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 09:27:51,523 - ERROR :     return self.func(*args)
2021-07-23 09:27:51,523 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 84, in on_button1
2021-07-23 09:27:51,523 - ERROR :     self.button1.config(relief=tk.SUNKEN)
2021-07-23 09:27:51,523 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1637, in configure
2021-07-23 09:27:51,523 - ERROR :     return self._configure('configure', cnf, kw)
2021-07-23 09:27:51,523 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1627, in _configure
2021-07-23 09:27:51,524 - ERROR :     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2021-07-23 09:27:51,524 - ERROR : _tkinter.TclError: invalid command name ".!toplevel3.!distributiondata.!button"
2021-07-23 09:28:15,309 - ERROR : Exception in Tkinter callback
2021-07-23 09:28:15,310 - ERROR : Traceback (most recent call last):
2021-07-23 09:28:15,310 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 09:28:15,310 - ERROR :     return self.func(*args)
2021-07-23 09:28:15,310 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 84, in on_button1
2021-07-23 09:28:15,310 - ERROR :     self.button1.config(relief=tk.SUNKEN)
2021-07-23 09:28:15,310 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1637, in configure
2021-07-23 09:28:15,310 - ERROR :     return self._configure('configure', cnf, kw)
2021-07-23 09:28:15,310 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1627, in _configure
2021-07-23 09:28:15,310 - ERROR :     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2021-07-23 09:28:15,310 - ERROR : _tkinter.TclError: invalid command name ".!toplevel4.!distributiondata.!button"
2021-07-23 09:30:03,691 - ERROR : Exception in Tkinter callback
2021-07-23 09:30:03,692 - ERROR : Traceback (most recent call last):
2021-07-23 09:30:03,692 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 09:30:03,692 - ERROR :     return self.func(*args)
2021-07-23 09:30:03,692 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 80, in on_button1
2021-07-23 09:30:03,692 - ERROR :     self.xl.ActiveSheet.Range(self.user_selection).Value = float(params[0])+float(params[1])
2021-07-23 09:30:03,692 - ERROR : IndexError: list index out of range
2021-07-23 09:38:02,251 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 09:38:02,252 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 09:38:02,302 - WARNING : aiohttp could not be imported. Async example will not work
Traceback (most recent call last):
  File "C:\Users\ethan\Documents\simExcel\examples\asyncfunc.py", line 24, in <module>
    import aiohttp
  File "build/x64/py38/res/release/pyxll.py", line 8206, in __import_hook
ModuleNotFoundError: No module named 'aiohttp'
2021-07-23 09:38:02,374 - INFO : This product is licensed to 
2021-07-23 09:38:02,374 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 09:38:12,337 - ERROR : Exception in Tkinter callback
2021-07-23 09:38:12,350 - ERROR : Traceback (most recent call last):
2021-07-23 09:38:12,350 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 09:38:12,350 - ERROR :     return self.func(*args)
2021-07-23 09:38:12,350 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 65, in on_button1
2021-07-23 09:38:12,350 - ERROR :     self.xl.Worksheets(self.distrInfoPageName).Activate()
2021-07-23 09:38:12,350 - ERROR :   File "C:\Users\ethan\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9\Sheets.py", line 120, in __call__
2021-07-23 09:38:12,350 - ERROR :     ret = self._oleobj_.InvokeTypes(0, LCID, 2, (9, 0), ((12, 1),),Index
2021-07-23 09:38:12,351 - ERROR : pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)
2021-07-23 09:38:22,109 - ERROR : Exception in Tkinter callback
2021-07-23 09:38:22,109 - ERROR : Traceback (most recent call last):
2021-07-23 09:38:22,109 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 09:38:22,109 - ERROR :     return self.func(*args)
2021-07-23 09:38:22,109 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 86, in on_button1
2021-07-23 09:38:22,109 - ERROR :     self.button1.config(relief=tk.SUNKEN)
2021-07-23 09:38:22,110 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1637, in configure
2021-07-23 09:38:22,110 - ERROR :     return self._configure('configure', cnf, kw)
2021-07-23 09:38:22,110 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1627, in _configure
2021-07-23 09:38:22,110 - ERROR :     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2021-07-23 09:38:22,110 - ERROR : _tkinter.TclError: invalid command name ".!toplevel8.!distributiondata.!button"
2021-07-23 09:40:00,471 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 09:40:00,471 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 09:40:00,511 - WARNING : aiohttp could not be imported. Async example will not work
Traceback (most recent call last):
  File "C:\Users\ethan\Documents\simExcel\examples\asyncfunc.py", line 24, in <module>
    import aiohttp
  File "build/x64/py38/res/release/pyxll.py", line 8206, in __import_hook
ModuleNotFoundError: No module named 'aiohttp'
2021-07-23 09:40:00,572 - INFO : This product is licensed to 
2021-07-23 09:40:00,572 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 09:40:05,638 - ERROR : Exception in Tkinter callback
2021-07-23 09:40:05,638 - ERROR : Traceback (most recent call last):
2021-07-23 09:40:05,638 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 09:40:05,638 - ERROR :     return self.func(*args)
2021-07-23 09:40:05,638 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 90, in on_button1
2021-07-23 09:40:05,638 - ERROR :     self.button1.config(relief=tk.SUNKEN)
2021-07-23 09:40:05,638 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1637, in configure
2021-07-23 09:40:05,638 - ERROR :     return self._configure('configure', cnf, kw)
2021-07-23 09:40:05,639 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1627, in _configure
2021-07-23 09:40:05,639 - ERROR :     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2021-07-23 09:40:05,639 - ERROR : _tkinter.TclError: invalid command name ".!toplevel9.!distributiondata.!button"
2021-07-23 09:41:04,937 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 09:41:04,937 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 09:41:04,984 - WARNING : aiohttp could not be imported. Async example will not work
Traceback (most recent call last):
  File "C:\Users\ethan\Documents\simExcel\examples\asyncfunc.py", line 24, in <module>
    import aiohttp
  File "build/x64/py38/res/release/pyxll.py", line 8206, in __import_hook
ModuleNotFoundError: No module named 'aiohttp'
2021-07-23 09:41:05,047 - INFO : This product is licensed to 
2021-07-23 09:41:05,047 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 09:58:19,807 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 09:58:19,807 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 09:58:19,852 - WARNING : aiohttp could not be imported. Async example will not work
Traceback (most recent call last):
  File "C:\Users\ethan\Documents\simExcel\examples\asyncfunc.py", line 24, in <module>
    import aiohttp
  File "build/x64/py38/res/release/pyxll.py", line 8206, in __import_hook
ModuleNotFoundError: No module named 'aiohttp'
2021-07-23 09:58:19,920 - INFO : This product is licensed to 
2021-07-23 09:58:19,920 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:05:49,044 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:05:49,044 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:05:49,079 - ERROR : Error reloading 'arrayfunctions'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'arrayfunctions'
2021-07-23 10:05:49,103 - ERROR : Error reloading 'asyncfunc'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'asyncfunc'
2021-07-23 10:05:49,105 - ERROR : Error reloading 'automation'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'automation'
2021-07-23 10:05:53,332 - INFO : This product is licensed to 
2021-07-23 10:05:53,332 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:05:53,338 - ERROR : Error loading 'arrayfunctions' : spec not found for the module 'arrayfunctions'
2021-07-23 10:05:53,338 - ERROR : Error loading 'asyncfunc' : spec not found for the module 'asyncfunc'
2021-07-23 10:05:53,339 - ERROR : Error loading 'automation' : spec not found for the module 'automation'
2021-07-23 10:06:06,286 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:06:06,287 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:06:06,332 - ERROR : Error reloading 'arrayfunctions'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'arrayfunctions'
2021-07-23 10:06:06,336 - ERROR : Error reloading 'asyncfunc'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'asyncfunc'
2021-07-23 10:06:06,338 - ERROR : Error reloading 'automation'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'automation'
2021-07-23 10:06:32,550 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:06:32,550 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:06:32,631 - INFO : This product is licensed to 
2021-07-23 10:06:32,631 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:07:23,166 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:07:23,166 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:07:23,201 - ERROR : Error reloading 'customtypes'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'customtypes'
2021-07-23 10:07:33,570 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:07:33,570 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:07:33,651 - INFO : This product is licensed to 
2021-07-23 10:07:33,651 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:08:27,632 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:08:27,632 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:08:29,444 - INFO : This product is licensed to 
2021-07-23 10:08:29,444 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:10:46,493 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:10:46,493 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:10:46,529 - ERROR : Error reloading 'objectcache'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'objectcache'
2021-07-23 10:10:46,535 - ERROR : Error reloading 'plotting_functions'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'plotting_functions'
2021-07-23 10:10:48,027 - INFO : This product is licensed to 
2021-07-23 10:10:48,027 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:10:48,033 - ERROR : Error loading 'objectcache' : spec not found for the module 'objectcache'
2021-07-23 10:10:48,034 - ERROR : Error loading 'plotting_functions' : spec not found for the module 'plotting_functions'
2021-07-23 10:10:50,195 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:10:50,196 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:10:50,229 - ERROR : Error reloading 'objectcache'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'objectcache'
2021-07-23 10:10:50,234 - ERROR : Error reloading 'plotting_functions'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'plotting_functions'
2021-07-23 10:11:19,618 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:11:19,618 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:11:19,694 - INFO : This product is licensed to 
2021-07-23 10:11:19,694 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:30:32,839 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:30:32,839 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:30:32,951 - INFO : This product is licensed to 
2021-07-23 10:30:32,951 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:31:36,930 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:31:36,930 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:31:37,014 - INFO : This product is licensed to 
2021-07-23 10:31:37,014 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:33:41,230 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:33:41,230 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:33:41,324 - INFO : This product is licensed to 
2021-07-23 10:33:41,324 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:34:41,985 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:34:41,986 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:34:43,833 - INFO : This product is licensed to 
2021-07-23 10:34:43,833 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:34:54,662 - ERROR : Exception in Tkinter callback
2021-07-23 10:34:54,664 - ERROR : Traceback (most recent call last):
2021-07-23 10:34:54,664 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:34:54,664 - ERROR :     return self.func(*args)
2021-07-23 10:34:54,664 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 91, in on_button1
2021-07-23 10:34:54,664 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:34:54,664 - ERROR : AttributeError: 'DistributionData' object has no attribute 'control'
2021-07-23 10:34:56,082 - ERROR : Exception in Tkinter callback
2021-07-23 10:34:56,082 - ERROR : Traceback (most recent call last):
2021-07-23 10:34:56,083 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:34:56,083 - ERROR :     return self.func(*args)
2021-07-23 10:34:56,083 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 91, in on_button1
2021-07-23 10:34:56,083 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:34:56,083 - ERROR : AttributeError: 'DistributionData' object has no attribute 'control'
2021-07-23 10:34:57,291 - ERROR : Exception in Tkinter callback
2021-07-23 10:34:57,291 - ERROR : Traceback (most recent call last):
2021-07-23 10:34:57,291 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:34:57,291 - ERROR :     return self.func(*args)
2021-07-23 10:34:57,291 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 91, in on_button1
2021-07-23 10:34:57,291 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:34:57,291 - ERROR : AttributeError: 'DistributionData' object has no attribute 'control'
2021-07-23 10:34:58,061 - ERROR : Exception in Tkinter callback
2021-07-23 10:34:58,061 - ERROR : Traceback (most recent call last):
2021-07-23 10:34:58,061 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:34:58,062 - ERROR :     return self.func(*args)
2021-07-23 10:34:58,062 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 91, in on_button1
2021-07-23 10:34:58,062 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:34:58,062 - ERROR : AttributeError: 'DistributionData' object has no attribute 'control'
2021-07-23 10:35:43,222 - ERROR : Exception in Tkinter callback
2021-07-23 10:35:43,222 - ERROR : Traceback (most recent call last):
2021-07-23 10:35:43,222 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:35:43,222 - ERROR :     return self.func(*args)
2021-07-23 10:35:43,222 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 91, in on_button1
2021-07-23 10:35:43,223 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:35:43,223 - ERROR : AttributeError: 'DistributionData' object has no attribute 'control'
2021-07-23 10:36:44,423 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:36:44,423 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:36:44,531 - INFO : This product is licensed to 
2021-07-23 10:36:44,531 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:37:07,198 - ERROR : Exception in Tkinter callback
2021-07-23 10:37:07,199 - ERROR : Traceback (most recent call last):
2021-07-23 10:37:07,199 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:37:07,199 - ERROR :     return self.func(*args)
2021-07-23 10:37:07,199 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 93, in on_button1
2021-07-23 10:37:07,199 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:37:07,199 - ERROR : TypeError: default_values() got an unexpected keyword argument 'distrInfoPageName'
2021-07-23 10:37:13,250 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:37:13,251 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:37:13,332 - INFO : This product is licensed to 
2021-07-23 10:37:13,332 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:37:20,646 - ERROR : Exception in Tkinter callback
2021-07-23 10:37:20,646 - ERROR : Traceback (most recent call last):
2021-07-23 10:37:20,647 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:37:20,647 - ERROR :     return self.func(*args)
2021-07-23 10:37:20,647 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 93, in on_button1
2021-07-23 10:37:20,647 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:37:20,647 - ERROR : TypeError: default_values() got an unexpected keyword argument 'distrInfoPageName'
2021-07-23 10:38:26,773 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:38:26,773 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:38:26,860 - INFO : This product is licensed to 
2021-07-23 10:38:26,860 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:38:32,872 - ERROR : Exception in Tkinter callback
2021-07-23 10:38:32,873 - ERROR : Traceback (most recent call last):
2021-07-23 10:38:32,873 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:38:32,873 - ERROR :     return self.func(*args)
2021-07-23 10:38:32,873 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 93, in on_button1
2021-07-23 10:38:32,873 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:38:32,873 - ERROR : TypeError: default_values() missing 1 required positional argument: 'distribution_id'
2021-07-23 10:38:33,970 - ERROR : Exception in Tkinter callback
2021-07-23 10:38:33,971 - ERROR : Traceback (most recent call last):
2021-07-23 10:38:33,971 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\tkinter\__init__.py", line 1883, in __call__
2021-07-23 10:38:33,971 - ERROR :     return self.func(*args)
2021-07-23 10:38:33,971 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\tkinter_frames.py", line 93, in on_button1
2021-07-23 10:38:33,971 - ERROR :     default_values(control=self.control, user_selection=self.user_selection,
2021-07-23 10:38:33,971 - ERROR : TypeError: default_values() missing 1 required positional argument: 'distribution_id'
2021-07-23 10:39:25,506 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 10:39:25,506 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 10:39:25,596 - INFO : This product is licensed to 
2021-07-23 10:39:25,596 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 10:39:36,127 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values'
2021-07-23 10:39:37,528 - ERROR : TypeError: default_values() missing 3 required positional arguments: 'distribution_id', 'user_selection', and 'params'
2021-07-23 11:50:39,239 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 11:50:39,239 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 11:50:39,455 - INFO : This product is licensed to 
2021-07-23 11:50:39,455 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 11:50:56,006 - ERROR : Error calling function cell_data
2021-07-23 11:50:56,021 - ERROR : Traceback (most recent call last):
2021-07-23 11:50:56,021 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 61, in cell_data
2021-07-23 11:50:56,021 - ERROR :     values = xl.ActiveSheet.Range(user_selection).Value.split(",")
2021-07-23 11:50:56,021 - ERROR : AttributeError: 'NoneType' object has no attribute 'split'
2021-07-23 11:51:05,056 - ERROR : Error calling function cell_data
2021-07-23 11:51:05,056 - ERROR : Traceback (most recent call last):
2021-07-23 11:51:05,056 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 49, in cell_data
2021-07-23 11:51:05,056 - ERROR :     xl.Selection.Value = "MultCellSelEr"
2021-07-23 11:51:05,056 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\__init__.py", line 493, in __setattr__
2021-07-23 11:51:05,071 - ERROR :     self._oleobj_.Invoke(*(args + (value,) + defArgs))
2021-07-23 11:51:05,071 - ERROR : pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)
2021-07-23 11:51:11,979 - ERROR : Error calling function cell_data
2021-07-23 11:51:11,979 - ERROR : Traceback (most recent call last):
2021-07-23 11:51:11,979 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 49, in cell_data
2021-07-23 11:51:11,979 - ERROR :     xl.Selection.Value = "MultCellSelEr"
2021-07-23 11:51:11,979 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\__init__.py", line 493, in __setattr__
2021-07-23 11:51:11,979 - ERROR :     self._oleobj_.Invoke(*(args + (value,) + defArgs))
2021-07-23 11:51:11,979 - ERROR : pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)
2021-07-23 12:00:10,176 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:00:10,176 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:00:11,896 - INFO : This product is licensed to 
2021-07-23 12:00:11,896 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:00:36,226 - ERROR : Error calling function cell_data
2021-07-23 12:00:36,226 - ERROR : Traceback (most recent call last):
2021-07-23 12:00:36,226 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 61, in cell_data
2021-07-23 12:00:36,226 - ERROR :     values = xl.ActiveSheet.Range(user_selection).Value.split(",")
2021-07-23 12:00:36,226 - ERROR : AttributeError: 'NoneType' object has no attribute 'split'
2021-07-23 12:01:30,131 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:01:30,131 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:01:30,224 - INFO : This product is licensed to 
2021-07-23 12:01:30,224 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:01:31,150 - ERROR : Error calling function cell_data
2021-07-23 12:01:31,150 - ERROR : Traceback (most recent call last):
2021-07-23 12:01:31,150 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 61, in cell_data
2021-07-23 12:01:31,150 - ERROR :     values = xl.ActiveSheet.Range(user_selection).Value.split(",")
2021-07-23 12:01:31,150 - ERROR : AttributeError: 'float' object has no attribute 'split'
2021-07-23 12:02:16,211 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values'
2021-07-23 12:02:27,687 - ERROR : TypeError: default_values() missing 3 required positional arguments: 'distribution_id', 'user_selection', and 'params'
2021-07-23 12:06:09,288 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:06:09,288 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:06:09,373 - INFO : This product is licensed to 
2021-07-23 12:06:09,373 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:06:14,991 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values'
2021-07-23 12:06:18,634 - ERROR : TypeError: default_values() missing 3 required positional arguments: 'distribution_id', 'user_selection', and 'params'
2021-07-23 12:06:55,121 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:06:55,121 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:06:55,225 - INFO : This product is licensed to 
2021-07-23 12:06:55,225 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:06:57,991 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values_wrapper'
2021-07-23 12:07:06,970 - ERROR : Traceback (most recent call last):
2021-07-23 12:07:06,970 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 39, in default_values_wrapper
2021-07-23 12:07:06,970 - ERROR :     distribution_id = data["distribution_id"]
2021-07-23 12:07:06,971 - ERROR : TypeError: 'NoneType' object is not subscriptable
2021-07-23 12:07:42,515 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values_wrapper'
2021-07-23 12:07:43,896 - ERROR : Traceback (most recent call last):
2021-07-23 12:07:43,896 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 39, in default_values_wrapper
2021-07-23 12:07:43,897 - ERROR :     distribution_id = data["distribution_id"]
2021-07-23 12:07:43,897 - ERROR : TypeError: 'NoneType' object is not subscriptable
2021-07-23 12:15:42,130 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:15:42,131 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:15:42,229 - INFO : This product is licensed to 
2021-07-23 12:15:42,229 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:15:45,968 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values_wrapper'
2021-07-23 12:15:52,417 - ERROR : Traceback (most recent call last):
2021-07-23 12:15:52,417 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 44, in default_values_wrapper
2021-07-23 12:15:52,417 - ERROR :     distribution_id = data["distribution_id"]
2021-07-23 12:15:52,417 - ERROR : TypeError: 'NoneType' object is not subscriptable
2021-07-23 12:18:02,607 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:18:02,607 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:18:02,694 - INFO : This product is licensed to 
2021-07-23 12:18:02,694 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:18:07,802 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values_wrapper'
2021-07-23 12:18:09,034 - ERROR : Traceback (most recent call last):
2021-07-23 12:18:09,034 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 42, in default_values_wrapper
2021-07-23 12:18:09,035 - ERROR :     data = cell_data(control=control)
2021-07-23 12:18:09,035 - ERROR : TypeError: cell_data() missing 1 required positional argument: 'cell_location'
2021-07-23 12:18:14,878 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values_wrapper'
2021-07-23 12:18:22,266 - ERROR : Traceback (most recent call last):
2021-07-23 12:18:22,266 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 42, in default_values_wrapper
2021-07-23 12:18:22,266 - ERROR :     data = cell_data(control=control)
2021-07-23 12:18:22,266 - ERROR : TypeError: cell_data() missing 1 required positional argument: 'cell_location'
2021-07-23 12:18:58,684 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:18:58,684 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:18:58,783 - INFO : This product is licensed to 
2021-07-23 12:18:58,783 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:19:02,533 - ERROR : Error calling ribbon function 'error_ribbon_functions.default_values_wrapper'
2021-07-23 12:19:09,927 - ERROR : Traceback (most recent call last):
2021-07-23 12:19:09,927 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 42, in default_values_wrapper
2021-07-23 12:19:09,927 - ERROR :     data = cell_data(control=control, cell_location=current_cell.Address)
2021-07-23 12:19:09,927 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 59, in cell_data
2021-07-23 12:19:09,927 - ERROR :     values = xl.ActiveSheet.Range(selection).Value.split(",")
2021-07-23 12:19:09,927 - ERROR : NameError: name 'selection' is not defined
2021-07-23 12:19:26,222 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:19:26,222 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:19:26,318 - INFO : This product is licensed to 
2021-07-23 12:19:26,318 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:24:20,338 - INFO : callbacks.on_close: PyXLL is closing
2021-07-23 12:34:02,426 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:34:02,426 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:34:04,145 - INFO : This product is licensed to 
2021-07-23 12:34:04,145 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:34:18,125 - ERROR : Error calling ribbon function 'ribbon_functions.display_distribution'
2021-07-23 12:34:19,396 - ERROR : Traceback (most recent call last):
2021-07-23 12:34:19,396 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 237, in display_distribution
2021-07-23 12:34:19,397 - ERROR :     vals = x.split(",")
2021-07-23 12:34:19,397 - ERROR : AttributeError: 'tuple' object has no attribute 'split'
2021-07-23 12:44:09,777 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:44:09,777 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:44:09,872 - INFO : This product is licensed to 
2021-07-23 12:44:09,872 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 12:44:17,083 - ERROR : Error calling ribbon function 'ribbon_functions.display_distribution'
2021-07-23 12:44:20,020 - ERROR : Traceback (most recent call last):
2021-07-23 12:44:20,021 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\__init__.py", line 490, in __setattr__
2021-07-23 12:44:20,021 - ERROR :     args, defArgs=self._prop_map_put_[attr]
2021-07-23 12:44:20,021 - ERROR : KeyError: 'Address'
2021-07-23 12:44:20,021 - ERROR : 
2021-07-23 12:44:20,021 - ERROR : During handling of the above exception, another exception occurred:
2021-07-23 12:44:20,021 - ERROR : 
2021-07-23 12:44:20,021 - ERROR : Traceback (most recent call last):
2021-07-23 12:44:20,022 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 234, in display_distribution
2021-07-23 12:44:20,022 - ERROR :     xl.Selection.Address = "MultCellSelEr"
2021-07-23 12:44:20,022 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\__init__.py", line 492, in __setattr__
2021-07-23 12:44:20,022 - ERROR :     raise AttributeError("'%s' object has no attribute '%s'" % (repr(self), attr))
2021-07-23 12:44:20,022 - ERROR : AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library.Range instance at 0x2147549443792>' object has no attribute 'Address'
2021-07-23 12:44:28,801 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 12:44:28,801 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 12:44:28,894 - INFO : This product is licensed to 
2021-07-23 12:44:28,894 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:13:17,893 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:13:17,893 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:13:17,993 - INFO : This product is licensed to 
2021-07-23 13:13:17,993 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:13:41,689 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:13:49,902 - ERROR : Traceback (most recent call last):
2021-07-23 13:13:49,902 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 64, in explainErrorWrapper
2021-07-23 13:13:49,902 - ERROR :     explainError(control=control, error_id="Oops!", 
2021-07-23 13:13:49,902 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 126, in explainError
2021-07-23 13:13:49,902 - ERROR :     frame = ErrorFrame(master=window)
2021-07-23 13:13:49,902 - ERROR : TypeError: __init__() missing 1 required positional argument: 'error_id'
2021-07-23 13:14:46,287 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:14:46,288 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:14:46,388 - INFO : This product is licensed to 
2021-07-23 13:14:46,388 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:14:49,624 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:14:53,256 - ERROR : Traceback (most recent call last):
2021-07-23 13:14:53,257 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 64, in explainErrorWrapper
2021-07-23 13:14:53,257 - ERROR :     explainError(control=control, error_id="Oops!", 
2021-07-23 13:14:53,257 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 126, in explainError
2021-07-23 13:14:53,257 - ERROR :     frame = ErrorFrame(master=window, error_id=error_id)
2021-07-23 13:14:53,258 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 103, in __init__
2021-07-23 13:14:53,258 - ERROR :     self.initUI()
2021-07-23 13:14:53,258 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 113, in initUI
2021-07-23 13:14:53,258 - ERROR :     T.insert(tk.END, self.error_messages_dictionary[self.error_id])
2021-07-23 13:14:53,258 - ERROR : AttributeError: 'ErrorFrame' object has no attribute 'error_messages_dictionary'
2021-07-23 13:15:17,773 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:15:17,774 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:15:17,860 - INFO : This product is licensed to 
2021-07-23 13:15:17,860 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:15:21,114 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:15:29,664 - ERROR : Traceback (most recent call last):
2021-07-23 13:15:29,664 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 64, in explainErrorWrapper
2021-07-23 13:15:29,665 - ERROR :     explainError(control=control, error_id="Oops!", 
2021-07-23 13:15:29,665 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 127, in explainError
2021-07-23 13:15:29,665 - ERROR :     frame = ErrorFrame(master=window, error_id=error_id)
2021-07-23 13:15:29,665 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 103, in __init__
2021-07-23 13:15:29,666 - ERROR :     self.initUI()
2021-07-23 13:15:29,666 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 114, in initUI
2021-07-23 13:15:29,666 - ERROR :     T.insert(tk.END, self.error_messages_dictionary[self.error_id])
2021-07-23 13:15:29,666 - ERROR : AttributeError: 'ErrorFrame' object has no attribute 'error_messages_dictionary'
2021-07-23 13:15:38,259 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:15:38,259 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:15:38,348 - INFO : This product is licensed to 
2021-07-23 13:15:38,348 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:15:41,910 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:15:46,920 - ERROR : Traceback (most recent call last):
2021-07-23 13:15:46,920 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 64, in explainErrorWrapper
2021-07-23 13:15:46,921 - ERROR :     explainError(control=control, error_id="Oops!", 
2021-07-23 13:15:46,921 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 127, in explainError
2021-07-23 13:15:46,921 - ERROR :     frame = ErrorFrame(master=window, error_id=error_id)
2021-07-23 13:15:46,921 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 103, in __init__
2021-07-23 13:15:46,921 - ERROR :     self.initUI()
2021-07-23 13:15:46,921 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 114, in initUI
2021-07-23 13:15:46,922 - ERROR :     T.insert(tk.END, self.error_messages_dictionary[self.error_id])
2021-07-23 13:15:46,922 - ERROR : AttributeError: 'ErrorFrame' object has no attribute 'error_messages_dictionary'
2021-07-23 13:15:49,404 - INFO : callbacks.on_close: PyXLL is closing
2021-07-23 13:16:43,960 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:16:43,960 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:16:45,659 - INFO : This product is licensed to 
2021-07-23 13:16:45,659 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:17:00,629 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:17:15,166 - ERROR : Traceback (most recent call last):
2021-07-23 13:17:15,166 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:17:15,167 - ERROR :     explainError(control=control, error_id=control.Selection.Value, 
2021-07-23 13:17:15,167 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:17:19,118 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:17:31,697 - ERROR : Traceback (most recent call last):
2021-07-23 13:17:31,697 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 64, in explainErrorWrapper
2021-07-23 13:17:31,697 - ERROR :     explainError(control=control, error_id="Oops!", 
2021-07-23 13:17:31,697 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 127, in explainError
2021-07-23 13:17:31,698 - ERROR :     frame = ErrorFrame(master=window, error_id=error_id)
2021-07-23 13:17:31,698 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 103, in __init__
2021-07-23 13:17:31,698 - ERROR :     self.initUI()
2021-07-23 13:17:31,698 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 114, in initUI
2021-07-23 13:17:31,698 - ERROR :     T.insert(tk.END, self.error_messages_dictionary[self.error_id])
2021-07-23 13:17:31,698 - ERROR : AttributeError: 'ErrorFrame' object has no attribute 'error_messages_dictionary'
2021-07-23 13:17:49,349 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:17:49,349 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:17:49,445 - INFO : This product is licensed to 
2021-07-23 13:17:49,445 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:18:09,274 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:18:09,274 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:18:09,361 - INFO : This product is licensed to 
2021-07-23 13:18:09,361 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:19:22,570 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:19:25,041 - ERROR : Traceback (most recent call last):
2021-07-23 13:19:25,042 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:19:25,042 - ERROR :     explainError(control=control, error_id=control.Selection.Value, 
2021-07-23 13:19:25,042 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:25:34,240 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:25:34,240 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:25:34,331 - INFO : This product is licensed to 
2021-07-23 13:25:34,331 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:25:54,605 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:25:54,605 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:25:54,706 - INFO : This product is licensed to 
2021-07-23 13:25:54,706 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:26:11,658 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:26:37,165 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:26:38,297 - ERROR : Traceback (most recent call last):
2021-07-23 13:26:38,297 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:26:38,298 - ERROR :     explainError(control=control, error_id=xl.Selection.Value, 
2021-07-23 13:26:38,298 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:26:41,267 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:26:41,267 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:26:41,355 - INFO : This product is licensed to 
2021-07-23 13:26:41,355 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:26:46,046 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:26:59,735 - ERROR : Traceback (most recent call last):
2021-07-23 13:26:59,735 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:26:59,735 - ERROR :     explainError(control=control, error_id=xl.Selection.Value, 
2021-07-23 13:26:59,735 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:29:11,691 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:29:12,982 - ERROR : Traceback (most recent call last):
2021-07-23 13:29:12,982 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:29:12,982 - ERROR :     explainError(control=control, error_id=xl.Selection.Value, 
2021-07-23 13:29:12,982 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:30:42,452 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:30:42,452 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:30:42,553 - INFO : This product is licensed to 
2021-07-23 13:30:42,553 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:30:48,488 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:30:56,790 - ERROR : Traceback (most recent call last):
2021-07-23 13:30:56,790 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:30:56,790 - ERROR :     error_id = xl.Selection.Value
2021-07-23 13:30:56,790 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:32:17,548 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:32:17,548 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:32:17,634 - INFO : This product is licensed to 
2021-07-23 13:32:17,634 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:32:21,481 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:32:23,864 - ERROR : Traceback (most recent call last):
2021-07-23 13:32:23,864 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:32:23,864 - ERROR :     error_id = xl.Selection.Value
2021-07-23 13:32:23,864 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:32:38,323 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:32:38,323 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:32:38,407 - INFO : This product is licensed to 
2021-07-23 13:32:38,407 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:32:42,433 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:32:44,310 - ERROR : Traceback (most recent call last):
2021-07-23 13:32:44,310 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:32:44,310 - ERROR :     else:
2021-07-23 13:32:44,310 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:32:46,214 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:32:55,847 - ERROR : Traceback (most recent call last):
2021-07-23 13:32:55,847 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:32:55,847 - ERROR :     else:
2021-07-23 13:32:55,847 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:34:14,662 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:34:14,662 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:34:14,755 - INFO : This product is licensed to 
2021-07-23 13:34:14,755 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:34:18,060 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:34:29,865 - ERROR : Traceback (most recent call last):
2021-07-23 13:34:29,865 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:34:29,865 - ERROR :     error_id = xl.ActiveSheet.Range(xl.Selection).Value
2021-07-23 13:34:29,865 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:36:02,378 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:36:07,247 - ERROR : Traceback (most recent call last):
2021-07-23 13:36:07,247 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:36:07,247 - ERROR :     error_id = xl.ActiveSheet.Range(xl.Selection).Value
2021-07-23 13:36:07,247 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:37:02,556 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:37:05,283 - ERROR : Traceback (most recent call last):
2021-07-23 13:37:05,284 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:37:05,284 - ERROR :     error_id = xl.ActiveSheet.Range(xl.Selection).Value
2021-07-23 13:37:05,284 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:38:53,992 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:38:53,992 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:38:54,076 - INFO : This product is licensed to 
2021-07-23 13:38:54,076 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:38:58,740 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:39:01,935 - ERROR : Traceback (most recent call last):
2021-07-23 13:39:01,935 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:39:01,935 - ERROR :     explainError(control=control, error_id=error_id,
2021-07-23 13:39:01,935 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:39:30,861 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:39:30,861 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:39:30,948 - INFO : This product is licensed to 
2021-07-23 13:39:30,948 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:39:35,593 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:39:39,658 - ERROR : Traceback (most recent call last):
2021-07-23 13:39:39,658 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:39:39,659 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:40:44,095 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:40:44,095 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:40:44,199 - INFO : This product is licensed to 
2021-07-23 13:40:44,199 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:40:48,485 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:40:50,751 - ERROR : Traceback (most recent call last):
2021-07-23 13:40:50,751 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-23 13:40:50,751 - ERROR : AttributeError: 'IRibbonControl' object has no attribute 'Selection'
2021-07-23 13:40:58,359 - INFO : callbacks.on_close: PyXLL is closing
2021-07-23 13:41:03,513 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:41:03,513 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:41:05,257 - INFO : This product is licensed to 
2021-07-23 13:41:05,257 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:41:17,713 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-23 13:41:24,062 - ERROR : Traceback (most recent call last):
2021-07-23 13:41:24,062 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 65, in explainErrorWrapper
2021-07-23 13:41:24,063 - ERROR :     error_id = xl.ActiveSheet.Range(xl.Selection).Value
2021-07-23 13:41:24,063 - ERROR :   File "C:\Users\ethan\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9\_Worksheet.py", line 239, in Range
2021-07-23 13:41:24,063 - ERROR :     ret = self._oleobj_.InvokeTypes(197, LCID, 2, (9, 0), ((12, 1), (12, 17)),Cell1
2021-07-23 13:41:24,063 - ERROR : pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)
2021-07-23 13:41:50,811 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:41:50,811 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:41:50,895 - INFO : This product is licensed to 
2021-07-23 13:41:50,895 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:42:41,593 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:42:41,593 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:42:41,678 - INFO : This product is licensed to 
2021-07-23 13:42:41,678 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 13:44:43,728 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 13:44:43,728 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 13:44:43,824 - INFO : This product is licensed to 
2021-07-23 13:44:43,824 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 14:07:54,336 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 14:07:54,336 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 14:07:54,378 - ERROR : Error reloading 'meta_variables'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 110
    text =
          ^
SyntaxError: invalid syntax
2021-07-23 14:07:54,394 - ERROR : Not reloading dependency error_ribbon_functions because of previous failure to reload meta_variables
2021-07-23 14:07:54,394 - ERROR : Not reloading dependency tkinter_frames because of previous failure to reload meta_variables
2021-07-23 14:07:54,394 - ERROR : Not reloading dependency examples.tkinter_frames because of previous failure to reload meta_variables
2021-07-23 14:07:54,395 - ERROR : Not reloading ribbon_functions because of previous failure to reload meta_variables
2021-07-23 14:07:57,615 - INFO : This product is licensed to 
2021-07-23 14:07:57,615 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 14:07:57,621 - ERROR : Error loading 'meta_variables' : invalid syntax (meta_variables.py, line 110)
2021-07-23 14:08:17,048 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 14:08:17,048 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 14:08:17,140 - INFO : This product is licensed to 
2021-07-23 14:08:17,140 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 14:09:58,196 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 14:09:58,197 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 14:09:58,285 - INFO : This product is licensed to 
2021-07-23 14:09:58,285 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 14:10:16,841 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 14:10:16,841 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 14:10:16,933 - INFO : This product is licensed to 
2021-07-23 14:10:16,933 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 14:10:28,883 - INFO : callbacks.on_close: PyXLL is closing
2021-07-23 14:10:46,802 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 14:10:46,803 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 14:10:48,597 - INFO : This product is licensed to 
2021-07-23 14:10:48,597 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 14:12:00,283 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 14:12:00,283 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 14:12:00,367 - INFO : This product is licensed to 
2021-07-23 14:12:00,367 - INFO : The license will expire on 2021-08-21 (29 days left)
2021-07-23 14:13:26,039 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-23 14:13:26,039 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-23 14:13:26,141 - INFO : This product is licensed to 
2021-07-23 14:13:26,141 - INFO : The license will expire on 2021-08-21 (29 days left)
